// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thoxvolmqzelyjqpwtjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRob3h2b2xtcXplbHlqcXB3dGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTYzMTcsImV4cCI6MjA3MjE5MjMxN30.2V_aWSRk65Eusb5hBmwMOKiQCqhVHbj13LpgoAyvL3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});